# This file is designed for Production & Staging environment

FROM python:3.6-jessie

LABEL maintainer="Data Platforms <data_platforms@theiconic.com.au>"

ARG SUPERSET_USER="superset"

RUN cp /usr/share/zoneinfo/Australia/Sydney /etc/localtime

# Add a normal user
RUN useradd --user-group --create-home --no-log-init --shell /bin/bash ${SUPERSET_USER}

# Configure environment
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    HOME=/home/superset

RUN apt-get update -y

# Install dependencies to fix `curl https support error` and `elaying package configuration warning`
RUN apt-get install -y apt-transport-https apt-utils

# Install superset dependencies
# https://superset.incubator.apache.org/installation.html#os-dependencies
RUN apt-get install -y build-essential libssl-dev \
    libffi-dev python3-dev libsasl2-dev libldap2-dev libxi-dev

# Install extra useful tool for development
RUN apt-get install -y vim less postgresql-client redis-tools

# Install nodejs for custom build
# https://superset.incubator.apache.org/installation.html#making-your-own-build
# https://nodejs.org/en/download/package-manager/
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -y nodejs


WORKDIR /home/superset

COPY requirements*.txt ./
COPY docker/requirements-extra.txt .
COPY theiconic/docker/superset/requirements-ti.txt .

#RUN cp $SUPERSET_DIR/requirements.txt .
#RUN cp $SUPERSET_DIR/requirements-dev.txt .
#RUN cp $SUPERSET_DIR/

RUN pip install --cache-dir /tmp/pip --upgrade setuptools pip \
    && pip install -r requirements.txt -r requirements-dev.txt -r requirements-extra.txt -r requirements-ti.txt \
    && rm -rf /tmp/pip

## THE ICONIC CUSTOM DEPENDENCIES
#RUN apt-get update && apt-get install -y libmysqlclient-dev libldap2-dev apt-transport-https
#
#
#
#RUN pip install -r requirements-ti.txt

# EMAIL REPORTS REQUIREMENTS
RUN apt-get install -y libgtk-3-dev libdbus-glib-1-dev libx11-xcb1

# INSTALLING FIREFOX
RUN wget -O firefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64" && \
    tar xjf firefoxSetup.tar.bz2 -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/local/bin/firefox && \
    rm firefoxSetup.tar.bz2

# INSTALLING GECKODRIVER
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz && \
    tar -xzf geckodriver-v0.24.0-linux64.tar.gz && \
    mv geckodriver /usr/local/bin/ && \
    rm geckodriver-v0.24.0-linux64.tar.gz


COPY theiconic/docker/superset/files/local/docker-entrypoint.sh /usr/local/bin/
COPY theiconic/docker/superset/files/local/docker-init.sh /usr/local/bin/
COPY theiconic/docker/superset/files/local/superset_config.py /superset_config.py
COPY theiconic/docker/superset/files/assets /assets

RUN chown -R superset:superset $HOME

RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-init.sh

ENV PATH=$HOME/$SUPERSET_DIR/superset/bin:$PATH \
    PYTHONPATH=$HOME/$SUPERSET_DIR/superset/:$PYTHONPATH

#USER superset

COPY . .

# BUILD ASSETS
RUN cd superset/assets \
    && npm ci \
    && npm run build \
    && rm -rf node_modules

RUN cp /assets/html/welcome.html ${SUPERSET_DIR}/superset/templates/superset/welcome.html
RUN cp /assets/html/navbar.html ${SUPERSET_DIR}/superset/templates/appbuilder/navbar.html
RUN cp /assets/html/navbar_right.html ${SUPERSET_DIR}/superset/templates/appbuilder/navbar_right.html
RUN cp /assets/html/traceback.html ${SUPERSET_DIR}/superset/traceback.html

RUN cp /assets/js/chartAction.js ${SUPERSET_DIR}/superset/assets/src/chart/chartAction.js

RUN cp /assets/css/bootstrap.min.css ${SUPERSET_DIR}/superset/static/assets/dist/bootstrap.min.css
RUN cp /assets/css/custom.css ${SUPERSET_DIR}/superset/static/assets/dist/custom.css

RUN cp /assets/images/favicon.png ${SUPERSET_DIR}/superset/static/assets/images/superset-logo@2x.png
RUN cp /assets/images/favicon.png ${SUPERSET_DIR}/superset/static/assets/dist/favicon.png

RUN cp /superset_config.py ${SUPERSET_DIR}/superset/
RUN cp /usr/local/bin/docker-init.sh ${SUPERSET_DIR}/superset/

RUN chown -R superset:superset $HOME

ENTRYPOINT ["docker-entrypoint.sh"]

HEALTHCHECK CMD ["curl", "-f", "http://localhost:8088/health"]

EXPOSE 8088
